d = new dTree('d');
d.config.closeSameLevel=true;
d.config.useIcons=false;
d.config.folderLinks = false;
d.add(0,-1,'');
d.add(1,0,'Laporan Eksport','');
d.add(2,1,'Daftar','');
d.add(3,2,'Penyata Bayaran Caj Perkhidmatan Ikan Eksport (ICCS 01E)','Papar_Pilihan.aspx?id=21&RptH=ICCS01E.rpt&RptB=ICCS01E_B.rpt&RptT=ICCS01E_T.rpt');
d.add(4,1,'Kategori','');
d.add(5,4,'Laporan Eksport Ikan Semua Kategori (SPSB 02(b)1(E))','Papar_Pilihan.aspx?id=23&RptH=SPSB02(B)1_E.rpt&RptB=SPSB02(B)1_EB.rpt&RptT=SPSB02(B)1_ET.rpt');		
d.add(6,4,'Laporan Daftar Eksport Ikan Proses (SPSB 02/02a(1)(E))','Papar_Pilihan.aspx?id=24&RptH=SPSB0202A(1)_E.rpt&RptB=SPSB0202A(1)_EB.rpt&RptT=SPSB0202A(1)_ET.rpt');		
d.add(7,4,'Laporan Daftar Eksport Ikan Hidup (SPSB 02/03a(1)(E))','Papar_Pilihan.aspx?id=25&RptH=SPSB0203A(1)_E.rpt&RptB=SPSB0203A(1)_EB.rpt&RptT=SPSB0203A(1)_ET.rpt');		
d.add(8,1,'Spesis','');
d.add(9,8,'Kuantiti, Nilai dan Purata Harga bagi Eksport Mengikut Jenis Ikan (ICCS 14E)','Papar_Pilihan.aspx?id=27&RptH=ICCS14E.rpt&RptB=ICCS14EB.rpt&RptT=ICCS14ET.rpt');		
d.add(10,8,'Kuantiti, Nilai dan Purata Harga bagi Eksport Mengikut Kumpulan Ikan (ICCS 21E)','Papar_Pilihan.aspx?id=28&RptH=ICCS21E.rpt&RptB=ICCS21EB.rpt&RptT=ICCS21ET.rpt');		
d.add(11,1,'Bentuk','');
d.add(12,11,'Kuantiti / Nilai Eksport Barangan Proses Mengikut Bentuk (ICCS 15E)','Papar_Pilihan.aspx?id=30&RptH=ICCS15E.rpt&RptB=ICCS15EB.rpt&RptT=ICCS15ET.rpt');		
d.add(13,1,'Destinasi','');
d.add(14,13,'Agihan Ikan Eksport Mengikut Destinasi Pasaran (SPSB 06a(E))','Papar_Pilihan.aspx?id=32&RptH=SPSB06AE.rpt&RptB=SPSB06AE_B.rpt&RptT=SPSB06AE_T.rpt');		
document.write(d);
