d = new dTree('d');
d.config.closeSameLevel=true;
d.config.useIcons=false;
d.config.folderLinks = false;
d.add(0,-1,'');
//d.add(1,0,'Laporan Import dan Transit','');
//d.add(2,1,'Daftar','');
//d.add(3,2,'Daftar Import dan Transit Ikan Mengikut Kenderaan (ICCS 20I)','Papar_Pilihan.aspx?id=3&rptH=ICCS20I.rpt&RptB=ICCS20I_B.rpt&RptT=ICCS20I_T.rpt');
//d.add(4,1,'Caj','');
//d.add(5,4,'Penyata Bayaran Caj Perkhidmatan Ikan Import (ICCS01I)','Papar_Pilihan.aspx?id=5&RptH=ICCS01I.rpt&RptB=ICCS01I_B.rpt&RptT=ICCS01I_T.rpt');
//d.add(6,1,'Kategori','');
//d.add(7,6,'Laporan Import Ikan Semua Kategori (SPSB 02(1)(a)(I))','Papar_Pilihan.aspx?id=7&RptH=SPSB02(1)(A)_I.rpt&RptB=SPSB02(1)(A)_IB.rpt&RptT=SPSB02(1)(A)_IT.rpt');
//d.add(8,6,'Laporan Daftar Import Ikan Proses (SPSB 02/02a(1)(I))','Papar_Pilihan.aspx?id=8&RptH=SPSB0202A(1)_I.rpt&RptB=SPSB0202A(1)_IB.rpt&RptT=SPSB0202A(1)_IT.rpt');
//d.add(9,6,'Laporan Daftar Import Ikan Hidup (SPSB 02/03a(1)(I))','Papar_Pilihan.aspx?id=9&RptH=SPSB0203A(1)_I.rpt&RptB=SPSB0203A(1)_IB.rpt&RptT=SPSB0203A(1)_IT.rpt');
//d.add(10,1,'Spesis','');
//d.add(11,10,'Kuantiti, Nilai dan Purata Harga bagi Import Mengikut Jenis Ikan (ICCS 14I)','Papar_Pilihan.aspx?id=11&RptH=ICCS14I.rpt&RptB=ICCS14IB.rpt&RptT=ICCS14IT.rpt');
//d.add(12,10,'Kuantiti, Nilai dan Purata Harga bagi Import Mengikut Kumpulan Ikan (ICCS 21I)','Papar_Pilihan.aspx?id=12&RptH=ICCS21I.rpt&RptB=ICCS21IB.rpt&RptT=ICCS21IT.rpt');
//d.add(13,1,'Bentuk','');
//d.add(14,13,'Kuantiti / Nilai Import Barangan Proses Mengikut Bentuk (ICCS 15I)','Papar_Pilihan.aspx?id=14&RptH=ICCS15I.rpt&RptB=ICCS15IB.rpt&RptT=ICCS15IT.rpt');
//d.add(15,1,'Destinasi (Transit)','');
//d.add(16,15,'Laporan Ikan Transit Mengikut Destinasi dan Jenis (ICCS 17I)','Papar_Pilihan.aspx?id=16&RptH=ICCS17I.rpt&RptB=ICCS17IB.rpt&RptT=ICCS17IT.rpt');
//d.add(17,1,'Destinasi (Import)','');
//d.add(18,17,'Agihan Ikan Import Mengikut Destinasi Pasaran (SPSB 06a(I))','Papar_Pilihan.aspx?id=18&RptH=SPSB06AI.rpt&RptB=SPSB06CI.rpt&RptT=SPSB06DI.rpt');
//d.add(19,0,'Laporan Eksport','');
//d.add(20,19,'Daftar','');
//d.add(21,20,'Penyata Bayaran Caj Perkhidmatan Ikan Eksport (ICCS 01E)','Papar_Pilihan.aspx?id=21&RptH=ICCS01E.rpt&RptB=ICCS01E_B.rpt&RptT=ICCS01E_T.rpt');
//d.add(22,19,'Kategori','');
//d.add(23,22,'Laporan Eksport Ikan Semua Kategori (SPSB 02(b)1(E))','Papar_Pilihan.aspx?id=23&RptH=SPSB02(B)1_E.rpt&RptB=SPSB02(B)1_EB.rpt&RptT=SPSB02(B)1_ET.rpt');		
//d.add(24,22,'Laporan Daftar Eksport Ikan Proses (SPSB 02/02a(1)(E))','Papar_Pilihan.aspx?id=24&RptH=SPSB0202A(1)_E.rpt&RptB=SPSB0202A(1)_EB.rpt&RptT=SPSB0202A(1)_ET.rpt');		
//d.add(25,22,'Laporan Daftar Eksport Ikan Hidup (SPSB 02/03a(1)(E))','Papar_Pilihan.aspx?id=25&RptH=SPSB0203A(1)_E.rpt&RptB=SPSB0203A(1)_EB.rpt&RptT=SPSB0203A(1)_ET.rpt');		
//d.add(26,19,'Spesis','');
//d.add(27,26,'Kuantiti, Nilai dan Purata Harga bagi Eksport Mengikut Jenis Ikan (ICCS 14E)','Papar_Pilihan.aspx?id=27&RptH=ICCS14E.rpt&RptB=ICCS14EB.rpt&RptT=ICCS14ET.rpt');		
//d.add(28,26,'Kuantiti, Nilai dan Purata Harga bagi Eksport Mengikut Kumpulan Ikan (ICCS 21E)','Papar_Pilihan.aspx?id=28&RptH=ICCS21E.rpt&RptB=ICCS21EB.rpt&RptT=ICCS21ET.rpt');		
//d.add(29,19,'Bentuk','');
//d.add(30,29,'Kuantiti / Nilai Eksport Barangan Proses Mengikut Bentuk (ICCS 15E)','Papar_Pilihan.aspx?id=30&RptH=ICCS15E.rpt&RptB=ICCS15EB.rpt&RptT=ICCS15ET.rpt');		
//d.add(31,19,'Destinasi','');
//d.add(32,31,'Agihan Ikan Eksport Mengikut Destinasi Pasaran (SPSB 06a(E))','Papar_Pilihan.aspx?id=32&RptH=SPSB06AE.rpt&RptB=SPSB06AE_B.rpt&RptT=SPSB06AE_T.rpt');		
//d.add(33,0,'Laporan Keaktifan','');		
//d.add(34,33,'Import','');		
//d.add(35,34,'Laporan Keaktifan Import Ikan Mengikut Pengimport (SPSB 03a(1i)(I) - Pengimport)','Papar_Pilihan.aspx?id=35&RptH=SPSB03(A)1_IPI.rpt&RptB=SPSB03(A)1_IPI.rpt&RptT=SPSB03(A)1_IPI.rpt');		
//d.add(36,34,'Laporan Keaktifan Import Ikan Mengikut Pengeksport (SPSB 03a(1e)(I) - Pengeksport)','Papar_Pilihan.aspx?id=36&RptH=SPSB03(A)1_IPE.rpt&RptB=SPSB03(A)1_IPE.rpt&RptT=SPSB03(A)1_IPE.rpt');		
//d.add(37,34,'Laporan Keaktifan Import Ikan Mengikut Pengimport dan Bentuk Ikan/Produk (SPSB 04c(1i(I) - Pengimport)','Papar_Pilihan.aspx?id=37&RptH=SPSB04C1_IPI.rpt&RptB=SPSB04C1_IPI.rpt&RptT=SPSB04C1_IPI.rpt');		
//d.add(38,34,'Laporan Keaktifan Import Ikan Mengikut Pengeksport dan Bentuk Ikan/Produk (SPSBN 04c(1e)(I) - Pengeksport)','Papar_Pilihan.aspx?id=38&RptH=SPSB04C1_IPE.rpt&RptB=SPSB04C1_IPE.rpt&RptT=SPSB04C1_IPE.rpt');		
//d.add(39,34,'Laporan Keaktifan Import Ikan Mengikut Agen Pengangkutan (SPSB 07(I)) ','Papar_Pilihan.aspx?id=39&RptH=SPSB07_I.rpt&RptB=SPSB07_I.rpt&RptT=SPSB07_I.rpt');		
//d.add(40,33,'Eksport','');		
//d.add(41,40,'Laporan Keaktifan Eksport Ikan Mengikut Pengimport (SPSB 03a(1e)(E) - Pengeksport)','Papar_Pilihan.aspx?id=41&RptH=SPSB03(A)1_EPI.rpt&RptB=SPSB03(A)1_EPI.rpt&RptT=SPSB03(A)1_EPI.rpt');		
//d.add(42,40,'Laporan Keaktifan Eksport Ikan Mengikut Pengeksport (SPSB 03a(1i)(E) - Pengimport)','Papar_Pilihan.aspx?id=42&RptH=SPSB03(A)1_EPE.rpt&RptB=SPSB03(A)1_EPE.rpt&RptT=SPSB03(A)1_EPE.rpt');		
//d.add(43,40,'Laporan Keaktifan Eksport Ikan Mengikut Pengimport dan Bentuk Ikan/Produk (SPSB 04c(1e(E) - Pengeksport)','Papar_Pilihan.aspx?id=43&RptH=SPSB04C1_EPI.rpt&RptB=SPSB04C1_EPI.rpt&RptT=SPSB04C1_EPI.rpt');		
//d.add(44,40,'Laporan Keaktifan Eksport Ikan Mengikut Pengeksport dan Bentuk Ikan/Produk (SPSBN 04c(1i)(E) - Pengimport)','Papar_Pilihan.aspx?id=44&RptH=SPSB04C1_EPE.rpt&RptB=SPSB04C1_EPE.rpt&RptT=SPSB04C1_EPE.rpt');		
//d.add(45,40,'Laporan Keaktifan Eksport Ikan Mengikut Agen Pengangkutan (SPSB 07(E)) ','Papar_Pilihan.aspx?id=45&RptH=SPSB07_E.rpt&RptB=SPSB07_E.rpt&RptT=SPSB07_E.rpt');		
d.add(1,0,'Laporan CFC (Caj)','');		
d.add(2,1,'Laporan Caj Kenderaan Masuk Melalui Pintu Utara','Papar_Pilihan.aspx?id=48&RptH=ICCS_CAJ01.rpt&RptB=ICCS_CAJ05.rpt&RptT=ICCS_CAJ09.rpt');		
d.add(3,2,'Laporan Caj Kenderaan Masuk Melalui Pintu Selatan','Papar_Pilihan.aspx?id=49&RptH=ICCS_CAJ02.rpt&RptB=ICCS_CAJ05.rpt&RptT=ICCS_CAJ09.rpt');		
d.add(4,3,'Laporan Caj Ikan Import / Transit (Kaunter Bayaran)','Papar_Pilihan.aspx?id=50&RptH=ICCS_CAJ03.rpt&RptB=ICCS_CAJ06.rpt&RptT=ICCS_CAJ10.rpt');		
d.add(5,4,'Laporan Import/Eksport/Transit','Papar_Pilihan.aspx?id=51&RptH=ICCS_CAJ04.rpt&RptB=ICCS_CAJ07.rpt&RptT=ICCS_CAJ11.rpt');		
//d.add(62,0,'Senarai Pemantauan Kompleks','');		
//d.add(63,62,'Daftar','');		
//d.add(64,63,'Laporan Daftar Kenderaan Masuk/Keluar (Harian) (SPSB 05) - Import/Eksport','Papar_Pilihan.aspx?id=64&rptH=SPSB05.RPT&RptB=SPSB05B.rpt&RptT=SPSB05T.rpt');	
//d.add(65,63,'Laporan Daftar Pemeriksaan Import Pegawai ','Papar_Pilihan.aspx?id=65&RptH=ICCS22I.rpt&RptB=ICCS22IB.rpt&RptT=ICCS22IT.rpt');	
//d.add(66,63,'Laporan Daftar Pemeriksaan Eksport Pegawai ','Papar_Pilihan.aspx?id=66&RptH=ICCS22E.rpt&RptB=ICCS22EB.rpt&RptT=ICCS22ET.rpt');	
//d.add(67,63,'Laporan Daftar Pengisytiharan Import Pengguna ','Papar_Pilihan.aspx?id=67&RptH=ICCS23I.rpt&RptB=ICCS23IB.rpt&RptT=ICCS23IT.rpt');	
//d.add(68,63,'Laporan Daftar Pengisytiharan Eksport Pengguna ','Papar_Pilihan.aspx?id=68&RptH=ICCS23E.rpt&RptB=ICCS23EB.rpt&RptT=ICCS23ET.rpt');	
//d.add(69,63,'Laporan Daftar Pembayaran Pengguna ','Papar_Pilihan.aspx?id=69&RptH=ICCS24I.rpt&RptB=ICCS24B.rpt&RptT=ICCS24T.rpt');	
//d.add(70,63,'Laporan Daftar Pendaftaran Pintu ','Papar_Pilihan.aspx?id=70&RptH=ICCS25I.rpt&RptB=ICCS25B.rpt&RptT=ICCS25T.rpt');	
document.write(d);
